// Code generated by protoc-gen-go. DO NOT EDIT.
// source: director.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Players struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_b16b4c8b6f26526d, []int{0}
}
func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (dst *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(dst, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

func (m *Players) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type Songs struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Players              []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Songs) Reset()         { *m = Songs{} }
func (m *Songs) String() string { return proto.CompactTextString(m) }
func (*Songs) ProtoMessage()    {}
func (*Songs) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_b16b4c8b6f26526d, []int{1}
}
func (m *Songs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Songs.Unmarshal(m, b)
}
func (m *Songs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Songs.Marshal(b, m, deterministic)
}
func (dst *Songs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Songs.Merge(dst, src)
}
func (m *Songs) XXX_Size() int {
	return xxx_messageInfo_Songs.Size(m)
}
func (m *Songs) XXX_DiscardUnknown() {
	xxx_messageInfo_Songs.DiscardUnknown(m)
}

var xxx_messageInfo_Songs proto.InternalMessageInfo

func (m *Songs) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *Songs) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

type Filter struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=playerName,proto3" json:"playerName,omitempty"`
	SongIds              string   `protobuf:"bytes,2,opt,name=songIds,proto3" json:"songIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_b16b4c8b6f26526d, []int{2}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *Filter) GetSongIds() string {
	if m != nil {
		return m.SongIds
	}
	return ""
}

type Player struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_b16b4c8b6f26526d, []int{3}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_b16b4c8b6f26526d, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PlayerReport struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mem                  int64    `protobuf:"varint,2,opt,name=mem,proto3" json:"mem,omitempty"`
	SongIds              []int64  `protobuf:"varint,3,rep,packed,name=songIds,proto3" json:"songIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerReport) Reset()         { *m = PlayerReport{} }
func (m *PlayerReport) String() string { return proto.CompactTextString(m) }
func (*PlayerReport) ProtoMessage()    {}
func (*PlayerReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_b16b4c8b6f26526d, []int{5}
}
func (m *PlayerReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerReport.Unmarshal(m, b)
}
func (m *PlayerReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerReport.Marshal(b, m, deterministic)
}
func (dst *PlayerReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerReport.Merge(dst, src)
}
func (m *PlayerReport) XXX_Size() int {
	return xxx_messageInfo_PlayerReport.Size(m)
}
func (m *PlayerReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerReport.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerReport proto.InternalMessageInfo

func (m *PlayerReport) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PlayerReport) GetMem() int64 {
	if m != nil {
		return m.Mem
	}
	return 0
}

func (m *PlayerReport) GetSongIds() []int64 {
	if m != nil {
		return m.SongIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Players)(nil), "proto.Players")
	proto.RegisterType((*Songs)(nil), "proto.Songs")
	proto.RegisterType((*Filter)(nil), "proto.Filter")
	proto.RegisterType((*Player)(nil), "proto.Player")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*PlayerReport)(nil), "proto.PlayerReport")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirectorClient is the client API for Director service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectorClient interface {
	GetPlayers(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Players, error)
	GetSongs(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Songs, error)
	Register(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Response, error)
	RemovePlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Response, error)
	Report(ctx context.Context, in *PlayerReport, opts ...grpc.CallOption) (*Response, error)
}

type directorClient struct {
	cc *grpc.ClientConn
}

func NewDirectorClient(cc *grpc.ClientConn) DirectorClient {
	return &directorClient{cc}
}

func (c *directorClient) GetPlayers(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Players, error) {
	out := new(Players)
	err := c.cc.Invoke(ctx, "/proto.Director/GetPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) GetSongs(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Songs, error) {
	out := new(Songs)
	err := c.cc.Invoke(ctx, "/proto.Director/GetSongs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) Register(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Director/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) RemovePlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Director/RemovePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) Report(ctx context.Context, in *PlayerReport, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Director/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectorServer is the server API for Director service.
type DirectorServer interface {
	GetPlayers(context.Context, *Filter) (*Players, error)
	GetSongs(context.Context, *Filter) (*Songs, error)
	Register(context.Context, *Player) (*Response, error)
	RemovePlayer(context.Context, *Player) (*Response, error)
	Report(context.Context, *PlayerReport) (*Response, error)
}

func RegisterDirectorServer(s *grpc.Server, srv DirectorServer) {
	s.RegisterService(&_Director_serviceDesc, srv)
}

func _Director_GetPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).GetPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Director/GetPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).GetPlayers(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_GetSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).GetSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Director/GetSongs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).GetSongs(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Director/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).Register(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_RemovePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).RemovePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Director/RemovePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).RemovePlayer(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Director/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).Report(ctx, req.(*PlayerReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _Director_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Director",
	HandlerType: (*DirectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayers",
			Handler:    _Director_GetPlayers_Handler,
		},
		{
			MethodName: "GetSongs",
			Handler:    _Director_GetSongs_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Director_Register_Handler,
		},
		{
			MethodName: "RemovePlayer",
			Handler:    _Director_RemovePlayer_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _Director_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "director.proto",
}

func init() { proto.RegisterFile("director.proto", fileDescriptor_director_b16b4c8b6f26526d) }

var fileDescriptor_director_b16b4c8b6f26526d = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0x57, 0xcb, 0xba, 0xf6, 0xe8, 0xa6, 0xc4, 0x97, 0x32, 0x44, 0x46, 0x5e, 0x9c, 0xa0,
	0x43, 0x1c, 0xf8, 0x01, 0x44, 0x1c, 0xbe, 0x88, 0x44, 0xbf, 0x40, 0x6d, 0x8f, 0x52, 0x58, 0x9b,
	0x92, 0x44, 0xc1, 0x2f, 0xee, 0xb3, 0x24, 0xb9, 0xe0, 0x26, 0x0a, 0x3e, 0xf5, 0xfe, 0x77, 0xf7,
	0xff, 0xf7, 0xf2, 0x83, 0x59, 0xdd, 0x2a, 0xac, 0x8c, 0x54, 0xab, 0x41, 0x49, 0x23, 0xd9, 0xd8,
	0x7d, 0xf8, 0x19, 0x4c, 0x9e, 0xb6, 0xe5, 0x07, 0x2a, 0xcd, 0x4e, 0x20, 0x2b, 0xeb, 0x5a, 0xa1,
	0xd6, 0xa8, 0x8b, 0x68, 0x11, 0x2f, 0x33, 0xf1, 0xdd, 0xe0, 0x6b, 0x18, 0x3f, 0xcb, 0xbe, 0xd1,
	0xec, 0x08, 0xe2, 0xb6, 0xf6, 0x0b, 0xb1, 0xb0, 0x25, 0x2b, 0x60, 0x32, 0xf8, 0x8c, 0xe2, 0xc0,
	0xd9, 0x82, 0xe4, 0xb7, 0x90, 0xdc, 0xb7, 0x5b, 0x83, 0x8a, 0x9d, 0x02, 0xf8, 0xe6, 0x63, 0xd9,
	0x61, 0x11, 0x2d, 0xa2, 0x65, 0x26, 0x76, 0x3a, 0x36, 0x43, 0xcb, 0xbe, 0x79, 0xa8, 0x6d, 0x86,
	0x1d, 0x06, 0xc9, 0x39, 0x24, 0xfe, 0x42, 0xbb, 0x43, 0xf7, 0x50, 0x40, 0x90, 0xfc, 0x06, 0x52,
	0x81, 0x7a, 0x90, 0xbd, 0xf6, 0x49, 0x6f, 0x55, 0x15, 0xb6, 0x52, 0x11, 0xa4, 0xbd, 0xbc, 0xd3,
	0x0d, 0xe5, 0xdb, 0x92, 0xbf, 0x40, 0xee, 0xb3, 0x05, 0x0e, 0x52, 0x99, 0xbf, 0xff, 0xe0, 0xbc,
	0xd8, 0x39, 0x6f, 0x2c, 0x6c, 0xb9, 0x7b, 0x71, 0xec, 0x58, 0x04, 0x79, 0xfd, 0x19, 0x41, 0x7a,
	0x47, 0xb4, 0xd9, 0x25, 0xc0, 0x06, 0x4d, 0x60, 0x3c, 0xf5, 0xf4, 0x57, 0x9e, 0xca, 0x7c, 0x46,
	0x92, 0xc6, 0x7c, 0xc4, 0xce, 0x21, 0xdd, 0xa0, 0xf1, 0xa4, 0x7f, 0x2c, 0xe7, 0x24, 0xdd, 0x90,
	0x8f, 0xd8, 0x85, 0x7d, 0x74, 0xd3, 0x6a, 0x8b, 0x77, 0xba, 0x17, 0x34, 0x3f, 0x24, 0x19, 0xa0,
	0xf0, 0x11, 0xbb, 0x82, 0x5c, 0x60, 0x27, 0xdf, 0x91, 0x60, 0xfe, 0xc7, 0x91, 0x10, 0x96, 0xe3,
	0xbd, 0x5d, 0xdf, 0xfc, 0xc5, 0xf1, 0x9a, 0xb8, 0xce, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc6,
	0xf7, 0x9c, 0xf7, 0x6c, 0x02, 0x00, 0x00,
}
